### PR TITLE
Fix extensions

### LINKED ISSUE #120: Flex props doesn't work properly
Hello,

I noted that now `Flex` is based on `Box` component: https://github.com/jxnblk/grid-styled/blob/master/src/Flex.js

Something is not working properly because when I use a `Box` component, the HTML tag rendered looks fine and the style are correctly applied:

```html
<footer class="sc-bwzfXH eYUrDm" role="contentinfo" flexdirection="column"></footer>
```

However, using `Flex` looks like it can't clean the specific props from the HTML tag, also styled are not applied properly

```html
<footer class="sc-htpNat irXZyd" role="contentinfo" pt="1" bg="darkBlue900"></footer>
``` 

I monkey patch my code in local following the [old way](https://github.com/jxnblk/grid-styled/commit/b58dbbcd4a6d1934157fb913d051711098575d96#diff-536fc7306c4dbbc05c91c9d209661a6fL14):

```jsx
const Flex = styled(Box)([],
  { display: 'flex' },
  display,
  textAlign,
  maxWidth
)

Flex.defaultProps = {
  textAlign: 'inherit',
  blacklist: [...Object.keys(FlexBase.propTypes), 'textAlign']
}

export default Flex
```

Now is working fine. I suppose the problem is the `is` inheritance

### PR DESCRIPTION
**Pull request by jxnblk**
Updates system-components to extend components passed with the `is` prop. Should fix #120

### CODE REVIEW

File: tests/__snapshots__/emotion.js.snap [hunk 1]
```diff
@@ -43,6 +43,7 @@ exports[`Box renders with props 1`] = `
 
 exports[`Flex renders 1`] = `
 .emotion-0 {
+  box-sizing: border-box;
```
Comment (jxnblk) [inline tests/__snapshots__/emotion.js.snap]: Guess emotion doesn't dedupe this
